# Generated by Django 5.2.3 on 2025-06-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndustryApp', '0003_material_method_machineusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='materials',
            field=models.ManyToManyField(to='IndustryApp.material'),
        ),
    ]
